=== ur1el0/OpenIT-Summer-Bootcamp-2026/day-1/hands-on lab/Part 1/books-schema.json
{
	"$schema": "https://json-schema.org/draft/2020-12/schema",
     "type": "array",
       "items": 
       {
        "type": "object",
        "required": ["id", "title", "authors", "published_year","available", "genres", "publisher"],
        "properties": 
        {
            "id": 
            {
                "type": "integer",
                "minimum": 1
            },
            "title": 
            {   
                "type": "string"
            },
            "authors": 
            {
                "type": "array",
                "minItems": 1,
                "items": 
                {
                    "type": "string",
                    "minLength": 1,
                    "maxLength": 255
                }
            },
            "published_year": 
            {
                "type" : "integer",
                "minimum": 1000,
                "maximum": 2026
            },
            "available": 
            {
                "type": "boolean"
            },
            "genres" : 
            {
                "type" : "array",
                "minItems": 2,
                "items": 
                {
                    "type": "string"
                }
            },
            "publisher": 
            {
                "type": "object",
                "properties": 
                {
                    "name": 
                    {
                        "type": "string"
                    },
                    "city": 
                    {
                        "type" : "string"
                    }
                }
            }
        }
    }
}

=== ur1el0/OpenIT-Summer-Bootcamp-2026/day-1/hands-on lab/Part 1/books.json
[
    {
        "id": 1,
        "title": "Harry Potter and the Sorcerer's Stone",
        "authors": ["J.K. Rowling"],
        "published_year": 1997,
        "available": true,
        "genres": ["Fantasy", "Adventure"],
        "publisher": {
            "name": "Bloomsbury",
            "city": "London"
        }
    },
    {
        "id": 2,
        "title": "The Hobbit",
        "authors": ["J.R.R. Tolkien"],
        "published_year": 1937,
        "available": false,
        "genres": ["Fantasy", "Classic"],
        "publisher": {
            "name": "George Allen & Unwin",
            "city": "London"
        }
    },
    {
        "id": 3,
        "title": "To Kill a Mockingbird",
        "authors": ["Harper Lee"],
        "published_year": 1960,
        "available": true,
        "genres": ["Fiction", "Classic"],
        "publisher": {
            "name": "J.B. Lippincott & Co.",
            "city": "Philadelphia"
        }
    },
    {
        "id": 4,
        "title": "1984",
        "authors": ["George Orwell"],
        "published_year": 1949,
        "available": true,
        "genres": ["Dystopian", "Science Fiction"],
        "publisher": {
            "name": "Secker & Warburg",
            "city": "London"
        }
    },
    {
        "id": 5,
        "title": "Pride and Prejudice",
        "authors": ["Jane Austen"],
        "published_year": 1813,
        "available": false,
        "genres": ["Romance", "Classic"],
        "publisher": {
            "name": "T. Egerton",
            "city": "London"
        }
    }
]
